### ISSUE TITLE
As a customer

### ISSUE THREAD

**Issue by vincenzopalazzo** [GreyTeam2020/GoOutSafe_Primer2020#105]
I want to manage my account information
to modify the telephone number, password, contact data, etc.

**Comment by vincenzopalazzo** [comment]
the logic for it is done, mybe the interface also? @francescofact

I'm sure that we miss the flask tests. but I can do it

**Comment by francescofact** [comment]
yes and no, if we want to modify all but the password yes. If we want to change the password it is not yet available

**Comment by vincenzopalazzo** [comment]
I will discuss today in class about the password @francescofact, I'm interested in the other information
