### ISSUE TITLE
Exception inside the PR 122

### ISSUE THREAD

**Issue by vincenzopalazzo** [GreyTeam2020/GoOutSafe_Primer2020#125]
../../.local/lib/python3.6/site-packages/flask/app.py:1950: in full_dispatch_request
    rv = self.dispatch_request()
../../.local/lib/python3.6/site-packages/flask/app.py:1936: in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
../../.local/lib/python3.6/site-packages/flask_login/utils.py:272: in decorated_view
    return func(*args, **kwargs)
monolith/auth.py:37: in f
    return func(*args, **kwargs)
monolith/views/restaurants.py:139: in my_reservations
    reservations_n=RestaurantServices.get_restaurant_people(restaurant_id),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

restaurant_id = 1

    @staticmethod
    def get_restaurant_people(restaurant_id: int):
        """
        Given the id of the restaurant return the number of people at lunch and dinner
        """
        openings = db.session.query(OpeningHours)\
            .filter(
                OpeningHours.week_day == datetime.today(),
                OpeningHours.restaurant_id == restaurant_id,
            ).first()
    
        tables = (
            db.session.query(RestaurantTable)
            .filter_by(restaurant_id=restaurant_id)
            .all()
        )
        tables_id = []
        for table in tables:
            tables_id.append(table.id)
    
        reservations_l = (
            db.session.query(Reservation)
            .filter(
                Reservation.table_id.in_(tables_id),
                extract("day", Reservation.reservation_date)
                == extract("day", datetime.today()),
                extract("month", Reservation.reservation_date)
                == extract("month", datetime.today()),
                extract("year", Reservation.reservation_date)
                == extract("year", datetime.today()),
                extract("hour", Reservation.reservation_date)
>               >= extract("hour", openings.open_lunch),
                extract("hour", Reservation.reservation_date)
                <= extract("hour", openings.close_lunch),
            )
            .all()
        )
E       AttributeError: 'NoneType' object has no attribute 'open_lunch'

**Comment by francescofact** [comment]
Maybe there isn't a restaurant with id=1 or it's not a valid restaurant

**Comment by francescofact** [comment]
I can fix it returning [0,0] if the restaurant has no opening hours. It would make sense, if you don't have opening hour you wouldn't have reservations
