### ISSUE TITLE
1.4 As a customer I want to see single restaurant profiles so that I can see its info and also precautionary measures followed by the restaurant

### ISSUE THREAD

**Issue by vincenzopalazzo** [GreyTeam2020/GoOutSafe_Primer2020#37]

**Comment by MariagiovannaRotundo** [comment]
Bisogna inserire il campo per indicare le misure prese dal ristorante per via del covid-19 (al momento c'è una frase standard, nel database è già presente il campo e nella pagina di un ristorante le info vengono già mostrate)

**Comment by MariagiovannaRotundo** [comment]
Solved
