### ISSUE TITLE
remove urser list after registration

### ISSUE THREAD

**Issue by vincenzopalazzo** [GreyTeam2020/GoOutSafe_Primer2020#4]
In a good manner to remove the list of users after register one.

For the moment is a good debug

**Comment by MariagiovannaRotundo** [comment]
I've changed it and after registration is like after login: you can see a list of restaurants ora add your own restaurants

**Comment by vincenzopalazzo** [comment]
Thanks @MariagiovannaRotundo close by https://github.com/GreyTeam2020/GoOutSafe_Primer2020/pull/10
