### ISSUE TITLE
Introduce the possibility to register the customer or to register the operator

### ISSUE THREAD

**Issue by vincenzopalazzo** [GreyTeam2020/GoOutSafe_Primer2020#83]
divide the login process

**Comment by francescofact** [comment]
Maybe we can keep the same login but different registration forms

**Comment by vincenzopalazzo** [comment]
This is done? @francescofact 

>Maybe we can keep the same login but different registration forms

I agree

**Comment by francescofact** [comment]
Not yet, this morning i will do it
