### ISSUE TITLE
As a customer/operator, I want to unregister so to have my data deleted

### ISSUE THREAD

**Issue by vincenzopalazzo** [GreyTeam2020/GoOutSafe_Primer2020#94]

**Comment by vincenzopalazzo** [comment]
Can you help me to implement the UI to unregister the user? @francescofact 

I can test and implement the logic!

**Comment by francescofact** [comment]
yes sure! maybe we can do that in the same page as the card for "editing user data (password, email, ...)"
i'll work on something

**Comment by vincenzopalazzo** [comment]
I agree @francescofact, maybe two buttom MODIFY|DELETE, with the same view of login page
